### ISSUE TITLE
cleaning project fails with exit 65 , unable to wipe iOS build artifacts

### ISSUE THREAD

**Issue by dillonkuester** [pmadruga/react-native-clean-project#104]
`
ℹ️  STARTED: "watchman cache clear (if watchman is installed)"
✅ FINISHED: "watchman cache clear (if watchman is installed)" task has finished running in 102ms.

ℹ️  STARTED: "wipe temporary caches"
✅ FINISHED: "wipe temporary caches" task has finished running in 21ms.

ℹ️  STARTED: "wipe iOS build artifacts"
/Users/me/repos/MobileApp/node_modules/react-native-clean-project/source/internals/executor.js:40
    throw new Error(
          ^

Error: 

Task "wipe iOS build artifacts" 
Error: No matching processes belonging to you were found
** CLEAN FAILED **

. 
Exit code: 65

    at executeTask (/Users/me/repos/Mobile-App/node_modules/react-native-clean-project/source/internals/executor.js:40:11)
    at async main (/Users/me/repos/Mobile-App/node_modules/react-native-clean-project/source/index.js:23:5)

Node.js v19.3.0`

**Comment by dillonkuester** [comment]
Under the hood the wipe iOS build artifacts command is running:   'rm -rf ios/build && (killall Xcode || true) && xcrun -k && cd ios && xcodebuild -alltargets clean && cd .. && rm -rf "$(getconf DARWIN_USER_CACHE_DIR)/org.llvm.clang/ModuleCache" && rm -rf "$(getconf DARWIN_USER_CACHE_DIR)/org.llvm.clang.$(whoami)/ModuleCache" && rm -fr ~/Library/Developer/Xcode/DerivedData/ && rm -fr ~/Library/Caches/com.apple.dt.Xcode/',
