### ISSUE TITLE
Task "update iOS Pods" Error: . Exit code: 1

### ISSUE THREAD

**Issue by mjstelly** [pmadruga/react-native-clean-project#111]
Running the command `npx react-native-clean-project` throws
```
STARTED: "update iOS Pods"
/Users/mstelly/.npm/_npx/7819efec56c4c663/node_modules/react-native-clean-project/source/internals/executor.js:40
    throw new Error(
          ^

Error:

Task "update iOS Pods"
Error: .
Exit code: 1


    at executeTask (/Users/mstelly/.npm/_npx/7819efec56c4c663/node_modules/react-native-clean-project/source/internals/executor.js:40:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/Users/mstelly/.npm/_npx/7819efec56c4c663/node_modules/react-native-clean-project/source/index.js:35:5)
```
React Native Info
```
System:
  OS: macOS 13.2.1
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 175.34 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 16.20.1
    path: ~/.nvm/versions/node/v16.20.1/bin/node
  Yarn:
    version: 3.6.1
    path: ~/.nvm/versions/node/v16.20.1/bin/yarn
  npm:
    version: 8.19.4
    path: ~/.nvm/versions/node/v16.20.1/bin/npm
  Watchman:
    version: 2023.07.24.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /Users/mstelly/.jenv/shims/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```
I haven't found any resolution with a web search. Any ideas why this is occurring and how to resolve it?

**Comment by hastom** [comment]
Try running `cd ios && pod update` to see the output. In my case it was react-native-permissions

**Comment by d1fferenz** [comment]
I got the same Error (see at the end of this comment) and it's actually misleading. The error is caused by a non working `pod install`. I ran `cd ios && pod install` separately  and found, that there was actually an error in my podfile. I'm in the middle of the upgrade process from RN 0.72.XX --> 0.74.XX an copied a wrong line from the upgrade helper in my local podfile.

```
Exit code: 1
    at executeTask (/Users/danieldierdorf/GitLab/rnhbapp/node_modules/react-native-clean-project/source/internals/executor.js:40:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/Users/danieldierdorf/GitLab/rnhbapp/node_modules/react-native-clean-project/source/index.js:35:5)
```
