### ISSUE TITLE
Getting error on react-native clean-project-auto command 0.64.1

### ISSUE THREAD

**Issue by Kailash23** [pmadruga/react-native-clean-project#81]
Getting error on react-native clean-project-auto

```
yarn run v1.22.10
$ react-native clean-project-auto

Executing fully-automated project clean.
Use 'react-native clean-project' for more control
Use `./node_modules/.bin/react-native-clean-project' for total control

Error running 'wipe iOS build artifacts': No matching processes belonging to you were found

✅  wipe android build folder task has finished running in 40ms.
✅  wipe temporary caches task has finished running in 32ms.
✅  npm ci task has finished running in 15ms.
✅  watchman cache clear (if watchman is installed) task has finished running in 66ms.
✅  wipe user iOS Pods cache task has finished running in 506ms.
Error running 'clean android project': 

Error running 'clean android project': FAILURE: Build failed with an exception.

* Where:

Error running 'clean android project': Script '/Users/kailashuniyal/Desktop/cwings-delivery-app/node_modules/react-native-unimodules/gradle.groovy' line: 34

* What went wrong:

Error running 'clean android project': A problem occurred evaluating settings 'CwingsDeliveryApp'.
> 
Error running 'clean android project':  (No such file or directory)

* Try:

Error running 'clean android project': Run with --stacktrace
Error running 'clean android project':  option to get the stack trace. Run with 
Error running 'clean android project': --info or --debug option to get more log output. Run with --scan
Error running 'clean android project':  to get full insights.


Error running 'clean android project': * Get more help at https://help.gradle.org


Error running 'clean android project': BUILD FAILED in 6s

❌  Command 'clean android project' failed with code: 1
/Users/kailashuniyal/Desktop/cwings-delivery-app/node_modules/@react-native-community/cli/build/index.js:99
    const message = err.message.replace(/\.$/, '');
                        ^

TypeError: Cannot read property 'message' of undefined
    at handleError (/Users/kailashuniyal/Desktop/cwings-delivery-app/node_modules/@react-native-community/cli/build/index.js:99:25)
    at Command.handleAction (/Users/kailashuniyal/Desktop/cwings-delivery-app/node_modules/@react-native-community/cli/build/index.js:189:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```
info Fetching system and libraries information...
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 902.64 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.19.1 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by KrisLau** [comment]
Getting the same error even though it worked fine yesterday

**Comment by pmadruga** [comment]
Sorry that this is happening to you. Can you move to #79 as it seems to be duplicated? Then I can get all the feedback there while I'm trying to debug this.

**Comment by KrisLau** [comment]
@pmadruga Will do and no worries, thanks for the amazing work on the package!
