### ISSUE TITLE
Clean Project Auto Failing

### ISSUE THREAD

**Issue by KrisLau** [pmadruga/react-native-clean-project#82]
Ran clean project auto in my project directory and got this error:
```
% react-native clean-project-auto

Executing fully-automated project clean.
Use 'react-native clean-project' for more control
Use `./node_modules/.bin/react-native-clean-project' for total control

Error running 'wipe iOS build artifacts': No matching processes belonging to you were found

Error running 'clean android project': /bin/sh: ./gradlew: Permission denied

❌  Command 'clean android project' failed with code: 126
/Users/newuser/Desktop/Prototype/node_modules/@react-native-community/cli/build/index.js:99
    const message = err.message.replace(/\.$/, '');
                        ^

TypeError: Cannot read property 'message' of undefined
    at handleError (/Users/newuser/Desktop/Prototype/node_modules/@react-native-community/cli/build/index.js:99:25)
    at Command.handleAction (/Users/newuser/Desktop/Prototype/node_modules/@react-native-community/cli/build/index.js:189:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
newuser@Epic-Mac-mini Prototype % 

```

**Comment by ElChapitan** [comment]
I just ran into this one as well, did you by chance come up with a solution yet?

**Comment by KrisLau** [comment]
@ElChapitan nope

**Comment by gabgagnon** [comment]
Same problem here.

**Comment by pmadruga** [comment]
Do you have any special permissions on the `./gradlew` folder?

**Comment by pmadruga** [comment]
Sorry that this is happening to you. Can you move to #79 as it seems to be duplicated? Then I can get all the feedback there while I'm trying to debug this.

**Comment by kwangjaeyoo** [comment]
Same problem
